### ISSUE TITLE
How to adapt the Methods as Blocks?

### ISSUE THREAD

**Issue by schreiby** [shannah/CN1ObjCBridge#2]
Hello, 

Thank you for this amazing library -- it really helps to manage the flow of the code. 

I was able to successfully integrate the [Methods as Blocks](https://github.com/shannah/CN1ObjCBridge#methods-as-blocks) for this method, as it parallels the example.

`+ (void)requestAuthorization:(void (^)(PHAuthorizationStatus status))handler;
`

Can  you please provide guidance as to how to adapt the following method:

`+ (void)requestAccessForMediaType:(AVMediaType)mediaType` 
                                    ` completionHandler:(void (^)(BOOL granted))handler;`

Specifically, is there a way to access the value of `granted`?

Thank you.

**Comment by shannah** [comment]
Something like this:

~~~~
eval("AVCaptureDevice.requestAccessForMediaType:completionHandler:", "video", Method.create(ArgType.Int, args->{
    boolean granted = Method.getArgAsBoolean(args[0]);
    if (granted) { // the status for authorized
      Log.p("We were granted access");
    }
}));
~~~~

Notes:

1. `AVMediaType` is just an NSString.  I think that the value of AVMediaTypeVideo is just "video", but you can double check this.
2. BOOL is really just an int.  That's why we use ArgType.Int.
